
# -------------------------------------------------------------------------------------------------
# The "idp" parameter is the short name ("IdP key") required for all commands.

idp = "myidp"

# -------------------------------------------------------------------------------------------------
# These parameters are required for multiregion commands.

# Operation environment, used for Terraform workspace name. Default is "prod"
env = "prod"

# AWS secondary region
region2 = "us-west-2"

# Terraform Cloud organization name.
org = "my-tfc-org"

# Terraform Cloud token.
tfc-token = ""

# -------------------------------------------------------------------------------------------------
# These additional parameters are for the "multiregion dns" command.

# AWS primary region
region = "us-east-1"

# "domain-name" is required
domain-name = "example.net"

# "cloudflare-token" is required and must have edit permission on the domain name specified in "domain-name"
cloudflare-token = ""
